### ISSUE TITLE
BUG (uncaught node.js error)

### ISSUE THREAD

**Issue by cdnguyen** [julienma/Bridget#26] opened 2013-04-10 07:32 UTC
![Screen shot 2013-04-10 at 9 31 37 AM](https://f.cloud.github.com/assets/459313/360926/c4277d88-a1b0-11e2-8658-14e75d6d6c6a.png)

**Comment by julienma** [comment] 2013-04-10 14:35
Closing as duplicate of #24.
Thanks though.

**Closed as completed by julienma** 2013-04-10 14:35 UTC
Labels: duplicate
